// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvPFmHEQ2b6TcoGGQt8qj951J-0KSTQdQ',
    appId: '1:151624932739:web:ba898b1db17caba1932ab6',
    messagingSenderId: '151624932739',
    projectId: 'colorsapp-691eb',
    authDomain: 'colorsapp-691eb.firebaseapp.com',
    storageBucket: 'colorsapp-691eb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr822GxT0AIQtZO6AxnYz129vbRB3PbKk',
    appId: '1:151624932739:android:0263a9d5cca0a3a8932ab6',
    messagingSenderId: '151624932739',
    projectId: 'colorsapp-691eb',
    storageBucket: 'colorsapp-691eb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIVVer1fza62sgrCnLG3s981sfZr8E0vI',
    appId: '1:151624932739:ios:5cffb10cf8c130c7932ab6',
    messagingSenderId: '151624932739',
    projectId: 'colorsapp-691eb',
    storageBucket: 'colorsapp-691eb.appspot.com',
    iosBundleId: 'com.example.colorsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIVVer1fza62sgrCnLG3s981sfZr8E0vI',
    appId: '1:151624932739:ios:36ec3e8f9d236677932ab6',
    messagingSenderId: '151624932739',
    projectId: 'colorsapp-691eb',
    storageBucket: 'colorsapp-691eb.appspot.com',
    iosBundleId: 'com.example.colorsApp.RunnerTests',
  );
}
